[tool.nuthatch]
filesystem = "gs://sheerwater-datalake/caches"
host = "postgres.shared.rhizaresearch.org"
port = 5432
database = "postgres"
username = "sheerwater_write"
driver = "postgresql"
raster_store = "gs://terracotta-files"
dynamic_config_path = "sheerwater.utils.secrets"
remote_cache_size = "256GB"

[tool.nuthatch.filesystem_options]
cache_timeout = 0

[tool.nuthatch.local]
filesystem = "~/.cache/nuthatch"

[tool.nuthatch.mirror-public]
filesystem = "gs://sheerwater-public-datalake/caches"
[tool.nuthatch.mirror-public.filesystem_options]
cache_timeout = 0
# Setting token to anon skips credential grabbing on public datalake
token = "anon"
