[tool.nuthatch]
filesystem = "gs://sheerwater-datalake/caches"
host = "postgres.shared.rhizaresearch.org"
port = 5432
database = "postgres"
username = "sheerwater_write"
driver = "postgresql"

[tool.nuthatch.terracotta]
filesystem = "gs://sheerwater-datalake/rasters"
override_path = "/mnt/sheerwater-datalake"
database = "terracotta"

[tool.nuthatch.filesystem_options]
cache_timeout = 0

[tool.nuthatch.local]
filesystem = "~/.cache/nuthatch"

[tool.nuthatch.mirror-public]
filesystem = "gs://sheerwater-public-datalake/caches"
[tool.nuthatch.mirror-public.filesystem_options]
cache_timeout = 0
# Setting token to anon skips credential grabbing on public datalake
token = "anon"
